# Generated by Django 5.1.1 on 2024-10-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_objectentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectentry',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
